
package de.trispeedys.resourceplanning.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ResourceInfoService", targetNamespace = "http://webservice.resourceplanning.trispeedys.de/", wsdlLocation = "http://localhost:8080/resourceplanning-bpm-0.0.1-SNAPSHOT/ResourceInfoWs?wsdl")
public class ResourceInfoService
    extends Service
{

    private final static URL RESOURCEINFOSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESOURCEINFOSERVICE_EXCEPTION;
    private final static QName RESOURCEINFOSERVICE_QNAME = new QName("http://webservice.resourceplanning.trispeedys.de/", "ResourceInfoService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/resourceplanning-bpm-0.0.1-SNAPSHOT/ResourceInfoWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESOURCEINFOSERVICE_WSDL_LOCATION = url;
        RESOURCEINFOSERVICE_EXCEPTION = e;
    }

    public ResourceInfoService() {
        super(__getWsdlLocation(), RESOURCEINFOSERVICE_QNAME);
    }

    public ResourceInfoService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESOURCEINFOSERVICE_QNAME, features);
    }

    public ResourceInfoService(URL wsdlLocation) {
        super(wsdlLocation, RESOURCEINFOSERVICE_QNAME);
    }

    public ResourceInfoService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESOURCEINFOSERVICE_QNAME, features);
    }

    public ResourceInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResourceInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ResourceInfo
     */
    @WebEndpoint(name = "ResourceInfoPort")
    public ResourceInfo getResourceInfoPort() {
        return super.getPort(new QName("http://webservice.resourceplanning.trispeedys.de/", "ResourceInfoPort"), ResourceInfo.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResourceInfo
     */
    @WebEndpoint(name = "ResourceInfoPort")
    public ResourceInfo getResourceInfoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.resourceplanning.trispeedys.de/", "ResourceInfoPort"), ResourceInfo.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESOURCEINFOSERVICE_EXCEPTION!= null) {
            throw RESOURCEINFOSERVICE_EXCEPTION;
        }
        return RESOURCEINFOSERVICE_WSDL_LOCATION;
    }

}
