
package de.trispeedys.resourceplanning.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestDataProviderService", targetNamespace = "http://webservice.resourceplanning.trispeedys.de/", wsdlLocation = "http://localhost:8080/resourceplanning-bpm-0.0.1-SNAPSHOT/TestDataProviderWs?wsdl")
public class TestDataProviderService
    extends Service
{

    private final static URL TESTDATAPROVIDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTDATAPROVIDERSERVICE_EXCEPTION;
    private final static QName TESTDATAPROVIDERSERVICE_QNAME = new QName("http://webservice.resourceplanning.trispeedys.de/", "TestDataProviderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/resourceplanning-bpm-0.0.1-SNAPSHOT/TestDataProviderWs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTDATAPROVIDERSERVICE_WSDL_LOCATION = url;
        TESTDATAPROVIDERSERVICE_EXCEPTION = e;
    }

    public TestDataProviderService() {
        super(__getWsdlLocation(), TESTDATAPROVIDERSERVICE_QNAME);
    }

    public TestDataProviderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTDATAPROVIDERSERVICE_QNAME, features);
    }

    public TestDataProviderService(URL wsdlLocation) {
        super(wsdlLocation, TESTDATAPROVIDERSERVICE_QNAME);
    }

    public TestDataProviderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTDATAPROVIDERSERVICE_QNAME, features);
    }

    public TestDataProviderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestDataProviderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestDataProvider
     */
    @WebEndpoint(name = "TestDataProviderPort")
    public TestDataProvider getTestDataProviderPort() {
        return super.getPort(new QName("http://webservice.resourceplanning.trispeedys.de/", "TestDataProviderPort"), TestDataProvider.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestDataProvider
     */
    @WebEndpoint(name = "TestDataProviderPort")
    public TestDataProvider getTestDataProviderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.resourceplanning.trispeedys.de/", "TestDataProviderPort"), TestDataProvider.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTDATAPROVIDERSERVICE_EXCEPTION!= null) {
            throw TESTDATAPROVIDERSERVICE_EXCEPTION;
        }
        return TESTDATAPROVIDERSERVICE_WSDL_LOCATION;
    }

}
